//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::account::Entity as Account;
pub use super::ad::Entity as Ad;
pub use super::category::Entity as Category;
pub use super::region::Entity as Region;
pub use super::session::Entity as Session;
pub use super::user::Entity as User;
pub use super::verification_token::Entity as VerificationToken;
